name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    release:
        types: [created] # 仅当创建 Release 时触发

env:
    PROJECT_NAME: ILP

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - id: commit-hash
              uses: prompt/actions-commit-hash@v3

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Ninja
              uses: ashutoshvarma/setup-ninja@master
              with:
                  version: 1.10.0

            - name: Set up MinGW-w64
              run: |
                  sudo apt update
                  sudo apt install -y mingw-w64

            # - name: Set up MinGW
            #   uses: egor-tensin/setup-mingw@v2

            - name: Linux Build
              run: |
                  echo "Build with commit hash ${{ steps.commit-hash.outputs.short }}"
                  cmake --preset=Linux
                  cmake --build ./build/Linux -j --config Release

            - name: Windows Build
              run: |
                  echo "Build with commit hash ${{ steps.commit-hash.outputs.short }}"
                  cmake --preset=Windows
                  cmake --build ./build/Windows -j --config Release

            - name: Linux Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Linux-${{ steps.commit-hash.outputs.short }}
                  path: ./build/Linux/${{ env.PROJECT_NAME }}

            - name: Windows Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Windows-${{ steps.commit-hash.outputs.short }}
                  path: ./build/Windows/${{ env.PROJECT_NAME }}.exe

    release:
        needs: build
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - id: commit-hash
              uses: prompt/actions-commit-hash@v3

            - name: Download Linux Artifact
              uses: actions/download-artifact@v4
              with:
                  name: Linux-${{ github.ref_name }}
                  path: ./release-artifacts/

            - name: Download Windows Artifact
              uses: actions/download-artifact@v4
              with:
                  name: Windows-${{ github.ref_name }}
                  path: ./release-artifacts/

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: "Release ${{ github.ref_name }}"
                  body: |
                      ## Changes in this release
                      - Auto-generated release from GitHub Actions.
                      - Commit: `${{ github.sha }}`
                  files: |
                      ./release-artifacts/${{ env.PROJECT_NAME }}
                      ./release-artifacts/${{ env.PROJECT_NAME }}.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # - name: Release
            #   uses: softprops/action-gh-release@v2
            #   if: startsWith(github.ref, 'refs/tags/')
            #   with:
            #       name: Release ${{ github.ref }}
            #       files: |
            #           ./build/Windows/${{ env.PROJECT_NAME }}.exe
            #           ./build/Linux/${{ env.PROJECT_NAME }}
